update ch1-2
cosname/rmarkdown-guide pull request #30
Opened 2021-05-07 08:17 UTC by enixam

2021-05-07 09:18 UTC, gaospecial requested changes

2021-05-07 09:18 UTC, gaospecial commented on 02-installation.Rmd
> +中国大陆的读者有可能遇到网络问题，这时可以在 RStudio 的 `Tools --> Global Options --> Packages` 将 Primary Cran Repository 更改为国内的镜像。也可以在 `install.pckages` 中设置 `repos` 参数
install.packages

2021-05-07 09:18 UTC, gaospecial commented on _output.yml
> +  css: css/styles.css
css 文件地址是故意改的吗？

2021-05-07 09:19 UTC, gaospecial commented
文字优美，格式严谨！

2021-05-07 09:24 UTC, enixam commented on _output.yml
> +  css: css/styles.css
这个是我粘过来的一个 css 样式模板文件，就把名称给改了

2021-05-07 09:38 UTC, gaospecial approved these changes

2021-05-07 09:38 UTC, gaospecial approved these changes

2021-05-07 09:39 UTC, gaospecial approved these changes

2021-05-07 09:40 UTC, gaospecial commented
有写权限的人 Review 后才会触发合并。
![image](https://user-images.githubusercontent.com/107597/117431003-49349680-af5b-11eb-982e-00407ac415be.png)

2021-05-08 03:46 UTC, enixam commented
> 好像又出现了换行符不一致的问题呀，如 _output.yml，style.css，packages.bib，rmarkdown-guide.Rproj。 不过这不是大问题，只是每次来一遍的话，评审会多花两秒时间。

之前已经设置过git的换行了呀，我再研究一下

2021-05-08 03:51 UTC, yihui commented
嗯，我给你们所有人写权限了，所以以后你们自己通过了评审就可以自己合并了。

2021-05-08 03:59 UTC, merged

2021-05-08 08:25 UTC, gaospecial commented
> > 好像又出现了换行符不一致的问题呀，如 _output.yml，style.css，packages.bib，rmarkdown-guide.Rproj。 不过这不是大问题，只是每次来一遍的话，评审会多花两秒时间。
> 
> 之前已经设置过git的换行了呀，我再研究一下

你那个设置被我清空了，为了解决 PNG 图片被转换的 bug。#28

2021-05-08 08:33 UTC, enixam commented
没事，我现在重新设置了一遍本地 git 的换行，应该已经行了