word xarigan
cosname/rmarkdown-guide pull request #39
Opened 2021-06-29 01:53 UTC by liangliangzhuang

2021-06-29 02:48 UTC, gaospecial requested changes

2021-06-29 02:48 UTC, gaospecial commented on 09-Word-document.Rmd
> +为了在 R 中处理 Office 文档更加容易，David Gohel 于 2018 年开始开发 **officedown** 包\index{R package!officedown} [@R-officedown]，目的是在 R Markdown 中加入一些 **officer**\index{R package!officer} [@R-officer] 特性。
\index 中间的 感叹号，而且出现了两次。

2021-06-29 02:48 UTC, gaospecial commented on 09-Word-document.Rmd
> +要从 R Markdown 生成 Word 文档，可以使用输出格式 `word_document`。如果希望在文档中包含交叉引用，可以考虑输出格式 `bookdown::word_document2`，详细说明可见[这](https://bookdown.org/yihui/rmarkdown-cookbook/cross-ref.html#cross-ref)。
我觉得需要把 word_document2 的功能整合到这个章节来介绍，这样最好。

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
> +目前，大多数非 R 语言的代码块都是独立执行的。例如，同一文档中的所有 `bash` 代码块都在各自的会话中单独执行，因此后面的 `bash` 代码块不能使用在先前 `bash` 代码块中创建的变量，更改后的工作目录(通过 `cd` )不会跨不同的 bash 块持久存在。只有 R、Python 和 Julia 代码块在同一个会话中执行。请注意，所有的R代码块都在同一个 R 会话中执行，所有的 P
“只有 R、Python 和 Julia 代码块在同一个会话中执行。” 这句话在这里没有起到很好的作用。

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
> +目前，大多数非 R 语言的代码块都是独立执行的。例如，同一文档中的所有 `bash` 代码块都在各自的会话中单独执行，因此后面的 `bash` 代码块不能使用在先前 `bash` 代码块中创建的变量，更改后的工作目录(通过 `cd` )不会跨不同的 bash 块持久存在。只有 R、Python 和 Julia 代码块在同一个会话中执行。请注意，所有的R代码块都在同一个 R 会话中执行，所有的 P
“但是可以从另一个会话访问或操作一个会话的对象” 不符合语言习惯

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
> +  # 源代码在optio ns$code
多一个空格

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
>  ## 用渐近线 Asymptote 创建图形 {#eng-asy}
译为：矢量图形语言 Asymptote，不宜直译。

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
> +在 **knitr** 中的 `stata` 引擎是相当有限的。Doug Hemken 已经通过 **Statamarkdown** 包 \index{R package!Statamarkdown} 中对其进行了实质性的扩展，该包可以通过Github中获得，地址为： https://github.com/Hemken/Statamarkdown。通过在线搜索 "Stata R Markdown
GitHub 前后空格

2021-06-29 02:48 UTC, gaospecial commented on 17-dashboards.Rmd
> +如果 rmd 文档中有多个一级结构的内容时，这时仪表盘会将每个一节结构分别显示为单独页面。下面给出一个简单的例子：
rmd -> R Markdown

2021-06-29 02:48 UTC, gaospecial commented on 17-dashboards.Rmd
>  这时得到的界面如图\@ref(fig:dashboard-social)下所示：
\@ref 前加空格，删掉“下”

2021-06-29 02:48 UTC, gaospecial commented on 16-with-other-language.Rmd
> +```{asy, sine-curve, fig.cap='将数据从 R 传递到渐近线以绘制图形', cache=TRUE, fig.width=6,fig.align='center',fig.retina=1, eval=eval_asy()}
直接用语言名称 Asymptote

2021-06-29 02:48 UTC, gaospecial commented on examples/PDF-document-in-chinese.log
> +This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex 2021.6.23)  28 JUN 2021 20:07
这个 log 文件应当不需要，可以删除

2021-06-29 02:48 UTC, gaospecial commented on examples/beamer-presentation-theme.log
> +This is XeTeX, Version 3.141592653-2.6-0.999993 (TeX Live 2021) (preloaded format=xelatex 2021.6.23)  28 JUN 2021 21:42
这个 log 文件应当不需要，可以删除

2021-06-29 02:48 UTC, gaospecial commented on examples/shiny-output-args.Rmd
> +title: 通过呈现函数来设置输出参数
render 术语翻译尚需在全文统一，Mark 一下。

2021-06-29 02:48 UTC, gaospecial commented on examples/shiny-output-args.Rmd
> +## 刷过图像(并存储数据)
英文标点

2021-07-06 03:06 UTC, gaospecial commented
@liangliangzhuang 这个 PR 需要进行修改后才能继续进行，望知悉。

修改方法：添加新的 Commit 在这个 PR 的源头（`liangliangzhuang: master`）即可。

2021-07-16 04:36 UTC, liangliangzhuang reviewed
ok

2021-07-16 04:36 UTC, liangliangzhuang commented on 17-dashboards.Rmd
> +如果 rmd 文档中有多个一级结构的内容时，这时仪表盘会将每个一节结构分别显示为单独页面。下面给出一个简单的例子：
ok

2021-07-16 04:59 UTC, liangliangzhuang commented
ok

2021-07-16 05:51 UTC, gaospecial approved these changes

2021-07-16 06:22 UTC, merged