update part 5
cosname/rmarkdown-guide pull request #40
Opened 2021-07-25 14:09 UTC by rucwyf

2021-07-26 05:13 UTC, gaospecial requested changes
浏览了一遍，发现有一些小问题。修改后就可以通过了。

2021-07-26 05:13 UTC, gaospecial commented on 21-workflow.Rmd
> +## 通过 Google Drive 对 Rmd 文档进行协作 {#google-drive}
备注：Google Drive 不能访问，这一块内容先放在这里，以后再看怎么办。

2021-07-26 05:13 UTC, gaospecial commented on 21-workflow.Rmd
> +## 参数化的报告 {#parameterized-reports}
备注：这部分内容与 @gaospecial 写的内容重叠了（https://cosname.github.io/rmarkdown-guide/custom-output.html#parameterized-report）。先保留容后讨论。

2021-07-26 08:14 UTC, enixam approved these changes

2021-07-26 08:16 UTC, enixam commented on 21-workflow.Rmd
> +## 通过 Google Drive 对 Rmd 文档进行协作 {#google-drive}
一些需要翻墙的服务是不是可以汇总到某个杂烩章节或者附录中介绍？

2021-07-26 14:29 UTC, rucwyf commented on 20-projects.Rmd
> +当你在处理比较大的项目或报告时，你可能不想把所有的文本和代码都放在一个R Markdown文档中，而是把它们组织成更小的单元。在本章中，我们将介绍一些方法，来帮助你更好地组织与R Markdown相关的多个文件。
我试了一下，加不加空格对最后生成的pdf没有差别，就都没加

2021-07-26 14:30 UTC, rucwyf commented on 20-projects.Rmd
> +如果你的R Markdown中有大量代码，则可以考虑将一些代码放入外部R脚本中，并通过 `source()`\index{source()} 或 `sys.source()`\index{sys.source()}来运行它们，例如：
这个也是，似乎会自动添加空格

2021-07-26 14:44 UTC, rucwyf commented on 21-workflow.Rmd
> +## 通过 Google Drive 对 Rmd 文档进行协作 {#google-drive}
还有别的需要翻墙的服务吗？如果只有这一部分的话是不是可以放到最后然后标注一下

2021-07-26 14:47 UTC, rucwyf commented on 21-workflow.Rmd
> +## 参数化的报告 {#parameterized-reports}
> 备注：这部分内容与 @gaospecial 写的内容重叠了（[https://cosname.github.io/rmarkdown-guide/custom-output.html#parameterized-report）。先保留容后讨论。](https://cosname.github.io/rmarkdown-guide/custom-output.html#parameterized-report%EF%BC%89%E3%80%82%E5%85%88%E4%BF%9D%E7%95%99%E5%AE%B9%E5%90%8E%E8%AE%A8%E8%AE%BA%E3%80%82)

这两部分最后可以融在一起，但感觉放在后面会好一些？你这部分我当时想的主要应该排版方面的工作，参数化文档这边和排版本身关系不大。当然想个其它的小节标题也是可以的。

2021-07-28 04:35 UTC, gaospecial approved these changes

2021-07-28 04:35 UTC, merged