完成第三和第四章
cosname/rmarkdown-guide pull request #42
Opened 2021-08-21 22:56 UTC by qiushiyan

2021-08-22 01:01 UTC, rucwyf requested changes

2021-08-22 01:01 UTC, rucwyf commented on 04-document-elements.Rmd
> +import_example_result("examples/prettydoc.Rmd")
用 \`r import_example('prettydoc.Rmd')\`  会不会好一些? 现在看到的是一张图, 而且很长, 放在书里看起来会不太方便

2021-08-22 03:21 UTC, qiushiyan commented on 04-document-elements.Rmd
> +import_example_result("examples/prettydoc.Rmd")
现在把例子文档里的一部分介绍内容放到了正文里，删掉了一些输出。

2021-08-22 06:02 UTC, gaospecial commented
## 第三章

这个地方，格式丢失了。

> `{r, fig.width = 7} # 更改 fig.width 为 7，其他选项不变 plot(mtcars)

注释与代码不匹配

>   complete(year, sex, name, fill = list(prop = 0)) %>% # 未进入前 10 时按最后一名处理

## 第四章

4.5 交叉引用失效

> 输出效果如图 @ref()

另，示例不应出现“邱逸轩”的名字（姓名权）

2021-08-22 06:46 UTC, gaospecial requested changes

2021-08-22 06:46 UTC, gaospecial commented on 02-installation.Rmd
> +```{r create-rmd-prompt, echo = FALSE}
需要添加 `fig.cap` 属性（否则交叉引用不能工作）

2021-08-22 06:46 UTC, gaospecial commented on 02-installation.Rmd
> +后文经常谈到的 "R Markdown 如何如何" 泛指 rmarkdown 包及一系列相关工具的功能与使用，如果特指 `rmarkdown` 包的功能或函数，则用小写字母。
包的名称统一使用加粗显示（而不使用代码标记）？

2021-08-22 06:46 UTC, gaospecial commented on 02-installation.Rmd
>  ## 安装 R Markdown
评论：R Markdown 应当是一种技术平台的统称，不局限于 **rmarkdown** 软件包。它的一些依赖关系如 **knitr**，**bookdown**，**tinytex** 等等，该如何解释给读者，需要后续更多的工作。

2021-08-22 06:46 UTC, gaospecial commented on 02-installation.Rmd
示例源代码在 HTML 预览中的行间距过大，不知道是什么原因造成的。请排查一下原因。

2021-08-22 06:46 UTC, gaospecial commented on 02-installation.Rmd
>  ## 安装 Tinytex
接下来的几段话结尾有时会缺少标点符号。

2021-08-22 06:46 UTC, gaospecial commented on 03-basics.Rmd
> +本章介绍使用 R Markdown 写作的必要基础知识。首先，我们简要介绍 R Markdown 的编译过程，了解 Knit 按钮为我们代劳的细节。随后，重点讲述了 R Markdown 文档的三种基本元素，包括
段尾加一冒号为宜。

2021-08-22 06:46 UTC, gaospecial commented on 03-basics.Rmd
> +不难发现，上面的代码块与源文档 `first-rmd.Rmd` 之间存在明确的文本对应关系。例如，在 R Markdown 文档 `## R Markdown` 后的前两个段落中，我们有
此段以及后续的几段中，结尾加一标点符号为宜。

2021-08-22 06:46 UTC, gaospecial commented on 03-basics.Rmd
>  ::: {.no-h-scroll}
为保证格式统一，对于 HTML 源代码区块不需要另行指定 CSS 样式。

2021-08-22 06:46 UTC, gaospecial commented on 04-document-elements.Rmd
> +`r import_example("examples/cross-reference.Rmd")`
交叉引用这个例子也太长了，拆分成多个部分（图片）展示效果会更佳。

2021-08-22 06:46 UTC, gaospecial commented on 04-document-elements.Rmd
> +
此示例建议去掉 TOC，以更加聚焦于编号的展示。

2021-08-22 06:46 UTC, gaospecial commented on 04-document-elements.Rmd
> +## 参考文献和引用
TODO：这一部分以后应当结合 Zotero 和 EndNote 等常用文献管理软件做适当扩展。

2021-08-22 06:46 UTC, gaospecial commented on 04-document-elements.Rmd
> +一个条目以 `@type{` 开始，`type` 表示该条参考的类型，可以识 `article`, `book`, `manual` 等。在类型之后的是引用标签，如 `R-base`，其他项包含参考的作者，组织，地址，日期和链接等信息。为了使用 `.bib` 文件中的条目，我们需要用 YAML 元数据中的 `bibliography` 加载一个或多个 `.bib` 文件：
对于本书涉及到的通用文件格式，如 CSL，bibtex，YAML，HTML，LaTeX 等，是否有必要专门写一附录？

2021-08-22 18:25 UTC, qiushiyan commented on 02-installation.Rmd
> +后文经常谈到的 "R Markdown 如何如何" 泛指 rmarkdown 包及一系列相关工具的功能与使用，如果特指 `rmarkdown` 包的功能或函数，则用小写字母。
我看 rmarkdown deifinitive guide 和 rmarkdown cookbook 是这样的习惯

2021-08-22 19:05 UTC, qiushiyan commented on 04-document-elements.Rmd
> +## 参考文献和引用
这部分我没有什么使用经验，其他作者可以参与一下。另外 RStudio 的图形编辑器似乎对它们的支持都不错。

2021-08-22 21:18 UTC, qiushiyan commented on 02-installation.Rmd
取消 css 类后解决。

2021-08-23 17:57 UTC, qiushiyan commented on 04-document-elements.Rmd
> +`r import_example("examples/cross-reference.Rmd")`
已经拆分为引用标题和引用图片表格两个部分。

2021-08-24 03:59 UTC, gaospecial approved these changes

2021-08-24 03:59 UTC, gaospecial commented on 05-typesetting.Rmd
> +> |   "众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。”此第三境也。
引号使用不规范

2021-08-24 03:59 UTC, gaospecial commented on 05-typesetting.Rmd
> +> |   "众里寻他千百度，蓦然回首，那人却在，灯火阑珊处。”此第三境也。
双引号使用不规范。

2021-08-24 04:00 UTC, gaospecial commented
这次的提交可能是因为行尾符设置的缘故，导致很多文件的内容都显示为已变动。

2021-08-24 04:01 UTC, merged