update chapter 3
cosname/rmarkdown-guide pull request #51
Opened 2021-10-14 10:06 UTC by gaospecial

主要进行了以下工作：

- 将 HTML 文档、PDF 文档 等几个章节的内容挪动到了 `03-document.Rmd` 文档中去；
- 在挪动的时候进行了一些修订，包括为小标题指定 ID，一些内容的调整；
- 在新目录中，Tinytex 安装的内容已经调整到软件安装部分，这部分文字在这里移除；
- 在处理 @liangliangzhuang 写作的 Xaringan 幻灯片部分的内容时，进行了一些必要的修订。

Authors:

- Gao, Chun-Hui
- Zhuang, Liang-Liang

2021-11-09 09:26 UTC, rucwyf reviewed
有点长，之后接着review，一些”你“、”我们“的表达可以全文搜索一下然后改掉，就不一一标注了。

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +Pandoc 大大扩展了 Markdown 的语法。更重要的是，Pandoc 使得将 Markdown 文档转换为多种输出格式成为可能。在本章中，我们将介绍各种文档输出格式的功能。在接下来的两章中，我们将分别介绍幻灯片格式和其他 R Markdown 扩展。
本章将介绍各种...
接下来的两章将分别介绍幻灯片格式和其他 R Markdown 扩展

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +HTML 技术是网络上精彩纷呈内容的呈现者，她不仅能够表现文字、图片、表格、公式等通用元素，还可以表达音乐、视频、交互动画等其它文档格式不能呈现的内容。严格意义上说，采用 HTML 技术呈现的文字、网站、幻灯片等都是 HTML 文档。不过这里，我们首先介绍的是如何通过 R Markdown 来生成一份独立的 **`.html`** 格式的文件。
建议把 ”因为 Markdown 技术在设计之初的输出格式就是 HTML，所以 HTML 文档不仅仅是最常用 R Markdown 输出格式，同时也拥有最丰富的功能。“ 放在 ”不过这里“ 的前面，逻辑通常一些，然后后面改成 ”本节将首先介绍如何通过 R Markdown 来生成一份独立的 **`.html`** 格式的文件。“

另外，建议先介绍一些 HTML 的全称：超文本标记语言（HyperText Markup Language）

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +前面提过，R Markdown 生成 HTML 文档的过程有一个中间步骤，就是 Markdown + HTML 模板。HTML 模板包括预定义的文档结构、 CSS 样式表和 JavaScript 动态网页功能等，所以最终渲染得到的 HTML 文档的一些功能可能依赖于特定 HTML 模板才能实现。
这一句有些技术性过强，如果可以的话能否通俗一些？

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +默认情况下，R Markdown 的 HTML 文档使用 `rmarkdown::html_document` 模板。除此之外， `rmarkdown` 之外的其它软件包也提供了各种不同类型的 HTML 模板文件（如 `bookdown::html_document2`，`pagedown::html_paged` 等）。因此，在这一部分我们先从 R Markdown 到 `html_docum
`rmarkdown` 软件包应加粗，而非以代码形式呈现

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
这里建议以一个目录的例子为引导

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +### By Product
这里改成中文吧，然后可以贴近生活一些

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +-   `.tabset-pills` 将为标签文字加上预设的 "pill"样式（图 \@ref(fig:html-tabset)）。
"pill"前后的空格问题

2021-11-09 09:26 UTC, rucwyf commented on 03-document.Rmd
> +代码高亮也有可选的多种样式，包括 `default`，`tango`，`pygments`，`kate`，`monchrome`，`espresso`，`zenburn`，`haddock`，`breezedark` 和 `textmate` 等。
再加一句：本节将以 `tango` 为例，感兴趣的读者可以自行尝试其他样式。

另外，可以加一张图来展示一下样式。

2021-11-15 02:22 UTC, rucwyf reviewed
再来一部分

2021-11-15 02:22 UTC, rucwyf commented on 03-document.Rmd
> +title: "Habits"
"Habits"中文

2021-11-15 02:22 UTC, rucwyf commented on 03-document.Rmd
> +title: "Habits"
"Habits"中文

2021-11-15 02:22 UTC, rucwyf commented on 03-document.Rmd
> +title: "Habits"
"Habits"中文

2021-11-15 02:22 UTC, rucwyf commented on 03-document.Rmd
> +为 MathJax 配置一个新的可用来源。
这句可以更详细一些

2021-11-15 07:06 UTC, gaospecial commented on 03-document.Rmd
> +-   `.tabset-pills` 将为标签文字加上预设的 "pill"样式（图 \@ref(fig:html-tabset)）。
示例中文化后，此处更新了示例的效果图。

2021-11-15 09:26 UTC, gaospecial commented on 03-document.Rmd
> +除了像上面那样导入一个预定义的样式表，你还可以直接在 R Markdown 中添加新的 CSS 定义。这种方法非常适合于个别定义。如果你的 CSS 代码很多，或者想要在其它 R Markdown 中使用同样的定义，可能放在自定义的样式表文件中更加合适（参见 \@ref(html-style-css)）。
我觉得还是把控制前移比较好。在此感谢不厌其烦的指出来:thumbs:

2021-11-15 10:10 UTC, gaospecial commented
> 有点长，之后接着review，一些”你“、”我们“的表达可以全文搜索一下然后改掉，就不一一标注了。

刚刚把全文检索修改了一下，之前没搞给审核过程添麻烦了。

2021-11-17 07:40 UTC, gaospecial commented on 03-document.Rmd
> +mtcars
这个问题倒不是很大。如果要采用成绩单数据的话，需要定义一个公共数据集。

2021-11-17 07:45 UTC, gaospecial commented on 03-document.Rmd
> +mtcars
做一个有年代气息感的学生成绩单，作为通用的演示数据怎么样？李雷、韩梅梅、马冬梅什么的等等。

2021-11-17 07:54 UTC, gaospecial commented on 03-document.Rmd
> +HTML 文档需要 [MathJax](https://www.mathjax.org)\index{MathJax} 脚本来渲染 Latex 和 MathML 公式，调用 [MathJax](https://www.mathjax.org) 的方式则可以通过 `mathjax` 参数来调整。
做了脚注。

2021-12-05 14:37 UTC, rucwyf requested changes
主要问题在于很多地方没有把英文改成中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +mtcars
我那章用了张三李四，可以先统一，最后改成他们我觉得也可

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +<!-- use draft.png to show that this is a draft -->
改为中文，包括下面几行对应的部分，以及 'Draft mode' 和 'Final version'

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +    <title>$title$</title>
标题用中文吧

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +title: "Habits"
标题使用中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +title: "An Important Report"
标题使用中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +title: "Habits"
标题使用中文，可以和前面的统一

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +  Parent HTML file.
中文，包括下面的 Child HTML file

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +% you may want to save a copy of \href before redefining it
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +% preamble
这里以及后面的preamble、body改成中文会不会好一些

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +
PDF这一章能否加入如何d导入LaTeX包的介绍？

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +## Getting up | What I like to do first thing
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +> - Bullet 1
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +This text is centered.
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +  - Bullet 1
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +This text is red
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +Content of the left column.
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +Content of the right column.
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +    x = "Cut",
这块改成中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +## .can-edit[You can edit this slide title]
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +## .can-edit.key-firstSlideTitle[Change this title and then reload the page]
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +Hello, .can-edit[world], and welcome to my talk!
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +## A few of my favorite things
中文（包括下面）

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +## This slide...
中文（包括下面）

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +...content...
中文

2021-12-05 14:37 UTC, rucwyf commented on 03-document.Rmd
> +title: "Untitled"
中文

2021-12-08 10:41 UTC, gaospecial commented on 03-document.Rmd
> +title: "Habits"
另外搜到了几处，一并修改为中文了。

2021-12-08 10:51 UTC, gaospecial commented on 03-document.Rmd
> +% preamble
我同时保留的中英文以相互参照。

2021-12-08 10:52 UTC, gaospecial commented on 03-document.Rmd
> +
这部分内容我不了解，要不你来完善吧。

2022-02-08 16:25 UTC, rucwyf requested changes

2022-02-09 02:26 UTC, gaospecial commented on 03-document.Rmd
> +如果想限制代码块的高度，特别是代码执行过程中输出内容的高度，还可以从相应内容的 CSS 样式上着手，即通过 `class-output` 和 `class-source` 来定义内容的高度。
已改正。

2022-02-15 11:58 UTC, rucwyf approved these changes

2022-02-15 11:58 UTC, merged