update 4-1，4-2
cosname/rmarkdown-guide pull request #59
Opened 2021-11-09 15:28 UTC by liangliangzhuang

2021-11-15 13:38 UTC, liangliangzhuang commented
大哥们有谁有空帮忙看下咯～

2021-11-30 11:31 UTC, gaospecial reviewed
主要有以下几个问题还可以进一步完善：

- “我们”，“你”等用法，包括中英文混排时的格式，不通用的缩略语等；
- 例子的完善（如汉化），另外建议在 SAS，Stata 等引擎用法的基础上，添加一些 Python 引擎使用的实例；
- 交叉引用；
- 有些内容还可以进一步扩展和完善，尽量不要总让读者去查网上的资料，比较重要的内容都可以直接写在图书中去。

PS：不好意思，之前审了一部分，忘记提交了。今天总算是完整过了一遍，但是有些地方可能仍然没有注意到。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +*R Markdown权威指南* ([Xie, Allaire, and Grolemund 2018](https://bookdown.org/yihui/rmarkdown-cookbook/other-languages.html#ref-rmarkdown2018)) 的[2.7节](https://bookdown.org/yihui/rmarkdown/language-engin
①是不是可以加入一些现实的例子？
②是本节，而非本章。
③我们、你的问题需要更改。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +首先，让我们通过注册一个自定义语言引擎来揭示语言引擎是如何工作的。
我们

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +你可以通过使用 `knitr::knit engines$set()` 方法注册一个自定义语言引擎。它接受一个函数作为输入，例如：
把“你”改成“用户”。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +  # 源代码在optio ns$code
中间多了一个空格。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +这样就已经注册了 `foo` 引擎，现在你可以使用以 ```` ```{foo}```` 开头的代码块了。
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +这个引擎函数中有一个 `options` 参数，它是代码块的块选项列表。你可以在 `options$code` 中以字符向量的形式访问块的源代码。例如，对于代码块：
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +接下来，我们展示一个名为 `py` 的另一种 `python` 引擎的示例^[实际上，你应该改用内置的 python 引擎，该引擎基于 **reticulate** 软件包，并且更好地支持 Python 代码块]。这个引擎是通过 R 函数 `system2()` 调用 `python` 命令来实现的：
“我们”，“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +为了充分理解以上引擎的功能，你需要了解以下内容：
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +1. 给定 Python 代码作为字符串（上述函数中的代码），我们可以通过命令行调用 `python -c 'code'` 执行代码。 那就是 `system2()` 所做的。 我们通过在  `system2()` 中指定 `stdout = TRUE` 来收集（文本）输出。
“我们”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +1. 你可以将块选项、源代码和文本输出传递给函数 `knitr::engine_output()`\index{knitr!engine\_output()} 以生成最终输出。这个函数处理常见的块选项，比如 `echo = FALSE` 和 `results = 'hide'`，所以你不需要注意这些情况。
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +**knitr** 中的许多语言引擎都是这样定义的(例如，使用 `system2()` 来执行与语言对应的命令)。如果你对技术细节感兴趣，你可以在这里的R源代码中查看大多数语言引擎的源代码
你

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +如果你觉得你的版本比现有的更好你甚至可以通过 `knitr::knit_engines$set()` 重写现有的语言引擎。但是，通常我们不建议你这样做，因为这可能会让熟悉现有引擎的用户感到惊讶，但我们无论如何都想让你意识到这种可能性。
“你”，“我们”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +现在我们可以使用新的引擎 `py`，例如：
“我们”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +我们知道你喜欢 Python，所以让我们把它说清楚： R Markdown 和 **knitr** 确实支持 Python\index{language engine!python}\index{Python}。
“我们”，“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +你可以像往常一样在 chunk 头中添加 chunk 选项，比如 `echo = FALSE` 或 `eval = FALSE` ，并且也支持使用 Python 中的 **matplotlib** 包绘图。
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +R Markdown 和 **knitr** 中的 Python 支持是 **reticulate** 包\index{R package!reticulate} [@R-reticulate]，这个包的一个重要特性是它允许 Python 和 R 之间的双向通信。例如，你可以在 R 会话中通过**reticulate**包中的 py 对象访问或创建 Python 变量：
①第一句话没写完整；
②“你”。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +有关 **reticulate** 的更多信息，您可以在下面查看它的文档
“您”也不能用。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +有时将代码块的内容写入外部文件，然后在其他代码块中使用此文件可能会很有用。当然，你可以通过 `writeLines()` 等 R 函数来实现这一点，但问题是，当内容相对较长或包含特殊字符时，传递给 `writeLines()` 的字符串可能看起来很笨拙。下面是将长字符串写入文件 `my-file.txt` 的示例：
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +writeLines("This is a long character string.
汉化。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +自 R 4.0.0 以来，这个问题已经大大缓解了，因为 R 开始支持 `r"( )"` 中的原始字符串(参见帮助页面 `?Quotes`)，而且你不需要记住所有关于特殊字符的规则。即使使用原始字符串，在代码块中显式地将长字符串写入文件仍然会让读者分心。
这个特性好像很好，我第一次听说，它具体的用法和优越性该如何在书中体现呢？

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +**knitr** 中的 `cat` 引擎\index{language engine!cat}为你提供了一种在代码块中呈现文本内容或将其写入外部文件的方法，而无需考虑有关 R 字符串的所有规则（例如，当需要字面上的反斜杠时，你需要双反斜杠）。
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +要将块内容写入文件，请在块选项 `engine.opts`\index{chunk option!engine.opts} 中指定文件路径，例如 `engine.opts = list(file = 'path/to/file')`。在引擎盖下，在 `engine.opts`\index{chunk option!engine.opts} 中指定的值列表将传递给该函数
“引擎盖”该如何理解？换一个更易懂的译法会不会更好。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +第一种方法是你可以在 Rmd 文档中嵌入一个 `css` 代码块，以使用 CSS\index{CSS}\index{language engine!css} 样式化元素。另一种方法是通过一些 R Markdown 输出格式(如，`html_document`)的 CSS 选项为 Pandoc 提供一个定制的 CSS 文件。 `cat` 引擎可以用来从 Rmd 编写这个 CSS 文件。
①“你”；
②Rmd = R Markdown。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> + `css` 代码块方法与此方法之间的唯一区别是，前一种方法将 CSS 代码写在输出文档的 `<body>` 标记内的位置（即，在代码块的位置），并且将 CSS 代码写在输出文档的 `<body>` 标记内。 后一种方法将 CSS 写入输出文档的 `<body>` 区域。输出文档中不会有任何实际的视觉差异。
这句话好像有点没说清楚，因为两种方法的说明文字是一样的。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +在6.1节中，我们介绍了如何将 LaTeX 代码添加到序言中，这需要一个外部 `.tex`  文件。也可以从 Rmd 生成此文件，这是一个示例：
①6.1 节改成交叉引用；
②“我们”，“你”的问题；
③Rmd 的问题。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +在上面的 `cat` 代码块中的 LaTeX 代码中，我们定义了 PDF 文档的页眉和页脚。如果我们还想在页脚中显示作者姓名，我们可以用选项`engine.opts = list(file = 'preamble.tex', append = TRUE)` 和 `code = sprintf('\\fancyfoot[LO,RE]{%s}', rmarkdown::metadata$author
好多“我们”。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +为了显示文件 `demo.yml` 确实已经生成，我们可以尝试使用 **yaml** 包 [@R-yaml] 将其读入 R。
“我们”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +你可以使用 `sas`  引擎\index{language engine!SAS}运行 SAS (https://www.sas.com) 代码。你需要确保 SAS 可执行文件在你的环境变量 `PATH` 中，或者(如果你不知道 `PATH` 是什么意思)通过 chunk 选项 `engine.path`\index{chunk option!engine.path} 来提供 SAS 可执行文
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +如果你安装了 Stata，你可以通过 `stata` 引擎\index{language engine!stata} Stata (https://www.stata.com) 来运行 Stata (https://www.stata.com) 代码。除非可以通过环境变量 `PATH` 找到 `stata` 可执行文件，否则你需要通过 chunk 选项 `engine.path`\index{c
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +渐近线 Asymptote (https://asymptote.sourceforge.io) 是矢量图形的强大语言。如果你已经安装了 Asymptote，那么可以使用 `asy` 引擎\index{Asymptote}\index{language engine!asy}在 R Markdown 中编写并运行 Asymptote 代码(有关安装的说明，请参阅其网站)。下面是从仓库 https
“你”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +如果出现这种错误，请参见 1.3 章节了解如何安装丢失的 LaTeX 包。
将 1.3 改为交叉引用。

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +在上面的 `asy` 块中，我们使用了 `settings.prc = false` 的设置。如果没有此设置，当输出格式为 PDF 时，渐近线将生成交互式 3D 图形。但是，交互图形只能在 Acrobat Reader 中查看。如果使用 Acrobat Reader，则可以与图形交互。例如，你可以用鼠标旋转图 \@ref(fig:elevation) 中的 3D 表面。
“我们”

2021-11-30 11:31 UTC, gaospecial commented on 06-operation.Rmd
> +现在我们展示一个示例，其中我们首先将在 R 中生成的数据保存到 CSV 文件中(下面是一个 R 代码块)：
“我们”

2022-02-16 03:32 UTC, gaospecial commented
@liangliangzhuang 请根据 Review 的已经对源文件进行修订。修订完成后，才能合并到主分支中去。

2022-02-16 03:36 UTC, gaospecial reviewed
请 @liangliangzhuang 修改一下。

2022-02-21 00:15 UTC, gaospecial requested changes
请参见 https://github.com/cosname/rmarkdown-guide/blob/master/Start.md#%E5%90%8D%E8%AF%8D ，规范行文过程中人称代词的使用。

2022-02-21 00:15 UTC, gaospecial commented on 06-operation.Rmd
> +在上面的 `cat` 代码块中的 LaTeX 代码中，我们定义了 PDF 文档的页眉和页脚。如果我们还想在页脚中显示作者姓名，我们可以用选项`engine.opts = list(file = 'preamble.tex', append = TRUE)` 和 `code = sprintf('\\fancyfoot[LO,RE]{%s}', rmarkdown::metadata$author
关于如何处理“我们”、“你”等字词的方法，请参见 https://github.com/cosname/rmarkdown-guide/blob/master/Start.md#%E5%90%8D%E8%AF%8D

2022-02-21 01:55 UTC, liangliangzhuang commented
@gaospecial 我将这个 pull 分成了两部分，第一部分根据建议修改后已经上传至：https://github.com/cosname/rmarkdown-guide/pull/61。第二部分需进一步修改，之后将以另一个分支上传。

2022-02-21 09:29 UTC, gaospecial approved these changes

2022-02-21 11:51 UTC, merged