6.2,6.5
cosname/rmarkdown-guide pull request #60
Opened 2022-02-15 11:57 UTC by rucwyf

2022-02-16 03:30 UTC, gaospecial requested changes

2022-02-16 03:30 UTC, gaospecial commented on 06-operation.Rmd
> +- **gt** [@R-gt]：这个R包允许用户将表格的不同部分组合在一起，例如表头（标题和副标题）、列标签、表格主体、行组标签以及表格的脚注，从而组成一个完整的表格，其中有些部分是可选择性添加的。还可以格式化数字，并为单元格添加背景阴影。目前 **gt** 主要支持 HTML 输出。^[如果需要支持其他输出格式，如 LaTeX 和 Word，**gtsummary** 包[@R-gtsumm
R 左右空格。

2022-02-16 03:30 UTC, gaospecial commented on 06-operation.Rmd
> +```{r, test-collapse}
是不是要加一个类似 code.from 的东西才能运行？

2022-02-16 03:30 UTC, gaospecial commented on 06-operation.Rmd
> +```{r, iris-asis}
同上

2022-02-20 13:10 UTC, rucwyf commented on 06-operation.Rmd
> +```{r, test-collapse}
是不需要的，可以正常编译

2022-02-21 00:11 UTC, gaospecial approved these changes

2022-02-21 00:11 UTC, merged