上传 5.1 shiny和 5.2 dashboards
cosname/rmarkdown-guide pull request #61
Opened 2022-02-21 01:53 UTC by liangliangzhuang

上传 5.1 shiny和 5.2 dashboards

2022-02-21 12:25 UTC, gaospecial requested changes

2022-02-21 12:25 UTC, gaospecial commented on 05-interaction.Rmd
> +当然 RStudio 官网也给出了该包的 [视频介绍](https://www.bing.com/search?q=flexdashboard&qs=n&form=QBLHCN&sp=-1&pq=flexdashboard&sc=9-13&sk=&cvid=B285D5FEF77A401AAE80C9FCB1E4DDDE) 以及一些案例，读者可以通过学习案例对应的代码实现快速入门。
链接并非 RStudio 官网的域名。

2022-02-21 12:25 UTC, gaospecial commented on 05-interaction.Rmd
> +
这部分内容不宜展示。

2022-02-21 12:25 UTC, gaospecial commented on 05-interaction.Rmd
> +在仪表盘中添加 Shiny\index{Shiny}，可以利用 viewers 更改参数，并显示实时结果。或者当仪表盘的数据发生变化时，让仪表盘进行实时更新（请参阅 **shiny** 包中的 `reactiveFileReader()` 和 `reactivePoll()` 函数）。这是通过将 `runtime: shiny` 添加到标准仪表盘文档来实现的，然后添加一个或多个输入控件或响应式表
什么是“viewers”？

2022-02-22 12:28 UTC, liangliangzhuang commented on 05-interaction.Rmd
> +当然 RStudio 官网也给出了该包的 [视频介绍](https://www.bing.com/search?q=flexdashboard&qs=n&form=QBLHCN&sp=-1&pq=flexdashboard&sc=9-13&sk=&cvid=B285D5FEF77A401AAE80C9FCB1E4DDDE) 以及一些案例，读者可以通过学习案例对应的代码实现快速入门。
已修改

2022-02-22 12:36 UTC, liangliangzhuang commented on 05-interaction.Rmd
> +在仪表盘中添加 Shiny\index{Shiny}，可以利用 viewers 更改参数，并显示实时结果。或者当仪表盘的数据发生变化时，让仪表盘进行实时更新（请参阅 **shiny** 包中的 `reactiveFileReader()` 和 `reactivePoll()` 函数）。这是通过将 `runtime: shiny` 添加到标准仪表盘文档来实现的，然后添加一个或多个输入控件或响应式表
指的是 编译后的交互界面。已修改

2022-02-22 12:36 UTC, liangliangzhuang commented
已修改以上意见

2022-02-23 00:16 UTC, gaospecial approved these changes

2022-02-23 00:31 UTC, merged

2022-02-23 02:59 UTC, gaospecial reviewed
不知道为啥内容没添加到位