add 04working
cosname/rmarkdown-guide pull request #62
Opened 2022-03-29 14:21 UTC by xiaolong-y

2022-04-01 09:04 UTC, gaospecial requested changes
详见行间批注。

2022-04-01 09:04 UTC, gaospecial commented on 04-working.Rmd
> +次书的本小节将通过一个对新手十分友好的案例来手把手的展示如何快速建立一个可满足用户基本需求的网站，以便用户可快速上手 blogdown，并根据自身需求在后期不断建设自己的个人网站。
有错别字。

2022-04-01 09:04 UTC, gaospecial commented on 04-working.Rmd
> +显示本地铺设成功后，你还可以点击在本地浏览器打开（在 RStudio 右上角的 `Show in new window`）来通过你的本地浏览器在本地浏览你的网页。只要网页项目在在本地浏览器中被打开后，任何在源文件上的改动都会自动在浏览器中实时进行加载，所以你不需要在每次改动后重复点击铺设网站。
尽量避免使用“你我他”，这是出版社的要求，需要遵循。

（**下同**）

2022-04-01 10:22 UTC, xiaolong-y commented
收到，多谢您的批注，错别字我立刻改，行文规范我之后注意。

2022-04-01 11:40 UTC, xiaolong-y reviewed
收到，立刻改正。

2022-04-02 01:55 UTC, gaospecial approved these changes

2022-04-02 02:09 UTC, merged