修改第 6.3 节“与其他语言的结合”内容
cosname/rmarkdown-guide pull request #79
Opened 2022-10-18 05:38 UTC by liangliangzhuang

备注：第 6.3.4 节“执行 Shell 脚本”，这里未做修改。该部分由王祎帆负责。

2022-10-24 01:10 UTC, gaospecial commented
有一个 icloud 的链接是多余的。

2022-10-24 01:47 UTC, gaospecial requested changes

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +接下来，将展示一个名为 `py` 的另一种 `python` 引擎示例^[这里只是一个简单的例子来演示如何自定义语言引擎。实际上，读者应该使用内置的 python 引擎，该引擎是基于 **reticulate** 软件包的，它能够更好地支持 Python 代码块]。这个引擎是通过 R 函数 `system2()` 调用 `python` 命令来实现的：
“Python 引擎”

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +1. 之后，将代码块选项、源代码和文本输出传递给函数 `knitr::engine_output()`\index{knitr!engine\_output()}，作为 最终输出结果。
“作为”后面多了一个空格。

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +·
多余的点。

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +<!-- ``` -->
如果这里的代码不需要，那么可以删掉。因为注释掉会让人难以理解这么做的目的。

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +writeLines("关于需要多少反斜杠时，是件让疼头疼的事。例如，到底是 '\t'、'\\t' 还是 '\\\\t'?", con = "my-file.txt")
这段话的表述有问题。

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
>  #### 在序言中包含 LaTeX 代码 {#write-latex}
“序言”这里的含义是什么？需要解释一下为什么要将 Latex 代码加入到序言中。

2022-10-24 01:47 UTC, gaospecial commented on 06-operation.Rmd
> +当出现这种错误时，读者可以参考书籍《R Markdown Cookbook》[@xie2020r]第 1.3 节，了解如何安装丢失的 LaTeX 包。
安装丢失的 Latex 包的内容本书中第二章也有。

2022-10-30 14:10 UTC, liangliangzhuang commented on 06-operation.Rmd
> +<!-- ``` -->
好的

2022-10-30 15:36 UTC, liangliangzhuang commented on 06-operation.Rmd
>  #### 在序言中包含 LaTeX 代码 {#write-latex}
这部分在第 3.2.4.1 节“通用文档部件”有了介绍，我在这里引一下吧。

2022-10-30 15:50 UTC, liangliangzhuang commented
> 有一个 icloud 的链接是多余的。

想问下这个在哪呀，找不到这个链接。

2022-10-30 15:51 UTC, liangliangzhuang commented
前面的已经根据要求修改过了，但是我 pull request 内容好像存在编译不了的问题。

2022-10-30 16:18 UTC, qiushiyan commented
> 前面的已经根据要求修改过了，但是我 pull request 内容好像存在编译不了的问题。

这个编译错误我改过了，如果没有其他问题解决 conflict 后可以合并

2022-10-31 02:11 UTC, liangliangzhuang commented
后续这个 Create 06-operation.Rmd 按错了，请无视

2022-10-31 08:33 UTC, gaospecial commented
> > 有一个 icloud 的链接是多余的。
> 
> 想问下这个在哪呀，找不到这个链接。

![image](https://user-images.githubusercontent.com/107597/198965488-deec663a-b1af-46c2-ad9d-837f75987ba0.png)

2022-10-31 15:39 UTC, qiushiyan commented
一些之前的改动在  [6b56ca0](https://github.com/cosname/rmarkdown-guide/pull/79/commits/6b56ca0edb8e90674ee4f9d9efbedb5d636b23a2) 覆盖掉了，是有意的吗？

2022-10-31 15:43 UTC, liangliangzhuang commented
> 一些之前的改动在 [6b56ca0](https://github.com/cosname/rmarkdown-guide/pull/79/commits/6b56ca0edb8e90674ee4f9d9efbedb5d636b23a2) 覆盖掉了，是有意的吗？

不是的，是我按错了，不好意思，[6b56ca0](https://github.com/cosname/rmarkdown-guide/pull/79/commits/6b56ca0edb8e90674ee4f9d9efbedb5d636b23a2)可以取消吗

2022-10-31 15:50 UTC, qiushiyan commented
> > 一些之前的改动在 [6b56ca0](https://github.com/cosname/rmarkdown-guide/pull/79/commits/6b56ca0edb8e90674ee4f9d9efbedb5d636b23a2) 覆盖掉了，是有意的吗？
> 
> 不是的，是我按错了，不好意思，[6b56ca0](https://github.com/cosname/rmarkdown-guide/pull/79/commits/6b56ca0edb8e90674ee4f9d9efbedb5d636b23a2)可以取消吗

没事，`git revert` 可以取消改动，我一会改一下

2022-11-03 08:42 UTC, rucwyf approved these changes

2022-11-04 02:37 UTC, gaospecial approved these changes

2022-11-04 02:38 UTC, merged