Polish chapter 3 and 7
cosname/rmarkdown-guide pull request #83
Opened 2022-11-11 05:26 UTC by qiushiyan

2022-11-11 07:39 UTC, gaospecial requested changes
只发现了一个小问题（见行内批注）。

另外，检查一下 png 图片，因为我发现所有图片在 GitHub 中提示“Unable to render rich display”。

2022-11-11 07:39 UTC, gaospecial commented on 03-document.Rmd
> +```{r html-code-highlight-example, fig.cap="(ref:figcap-html-code-highlight-example)", fig.show="hold", out.width="70%", echo=FALSE, echo=FALSE}
多了一个 echo

2022-11-11 17:15 UTC, qiushiyan commented on 03-document.Rmd
> +```{r html-code-highlight-example, fig.cap="(ref:figcap-html-code-highlight-example)", fig.show="hold", out.width="70%", echo=FALSE, echo=FALSE}
是 `df-print-example` 的那些图片吗？我 Github 和本地编译显示都没问题

<img width="1513" alt="image" src="https://user-images.githubusercontent.com/48123899/201393976-2865e74f-7f73-4d1f-bf4a-de22d9dcc29d.png">

2022-11-13 11:06 UTC, gaospecial approved these changes

2022-11-13 11:06 UTC, merged