各章的小修改
cosname/rmarkdown-guide pull request #85
Opened 2022-12-03 22:03 UTC by qiushiyan

2022-12-07 03:07 UTC, rucwyf requested changes

2022-12-07 03:07 UTC, rucwyf commented on 01-intro.Rmd
> +rmarkdown 包内置的网站功能较为简单。**blogdown** 包 [@R-blogdown] 提供了更复杂的网站功能，它使用了开源的网站工具：Hugo。Hugo 是目前速度最快，最受欢迎的静态网站生成器之一。一般用户通常需要在命令行调用 Hugo，不过作为幸福的 R 用户，读者可以照常写作 R Markdown 文档，随后调用 blogdown 函数操作 Hugo 编译，最后生成网站。
同理，包名称应该加粗。另外 blogdown 是个包吧，不是一个函数，建议改为 
”随后调用 **blogdown** 包中封装好的函数操作 Hugo 编译“，

2022-12-07 03:07 UTC, rucwyf commented on 02-base.Rmd
> +You can also embed plots, for example:。
这一部分应该全部改为中文

2022-12-08 16:23 UTC, qiushiyan commented on 02-base.Rmd
> +You can also embed plots, for example:。
这里是 R Markdown 自带的模版吧，我想让读者一开始能直接用现成的内容，不用从书里粘贴中文再复制编辑器里

2022-12-08 16:23 UTC, qiushiyan commented on 02-base.Rmd
> +You can also embed plots, for example:。
或者我们可以有一个和书配套的 R 包专门放书里各种例子的模版

2022-12-09 02:47 UTC, gaospecial commented on 02-base.Rmd
> +You can also embed plots, for example:。
如果说是自带模板的话，用原文比较好。因为这样读者会有统一的体验。

2022-12-11 12:34 UTC, rucwyf commented on 02-base.Rmd
> +You can also embed plots, for example:。
嗯嗯那这样也行，可以标明是一下自带模板？

2022-12-18 11:21 UTC, rucwyf approved these changes

2022-12-18 11:21 UTC, merged